'''
Write a function to compute 5/0 and use
try/except to catch the exceptions.
'''
try:
    answer=5/0
except:
    print("\n\nNull error can't divide by zero\n\n")
